name: Validate group contributor change
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine base
        id: base
        run: |
          echo "base_ref=${{ github.base_ref || 'main' }}" >> "$GITHUB_OUTPUT"

      - name: Fetch base
        run: |
          git fetch --no-tags --depth=1 origin "${{ steps.base.outputs.base_ref }}:${{ steps.base.outputs.base_ref }}"

      - name: List changed files
        id: diff
        run: |
          CHANGED="$(git diff --name-only ${{ steps.base.outputs.base_ref }}...HEAD)"
          echo "$CHANGED"
          printf 'files<<EOF\n%s\nEOF\n' "$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Ensure exactly one root contributors file changed
        id: onefile
        run: |
          echo "${{ steps.diff.outputs.files }}" | awk 'NF' > /tmp/changed.txt

          # Only allow files that match at repo root: G<number>-CONTRIBUTORS.md
          DISALLOWED=$(grep -vE '^G[0-9]+-CONTRIBUTORS\.md$' /tmp/changed.txt || true)
          if [ -n "$DISALLOWED" ]; then
            echo "❌ Only edit your group's contributors file at the repo root (e.g., G1-CONTRIBUTORS.md). Disallowed changes:"; echo "$DISALLOWED"; exit 1
          fi

          COUNT=$(wc -l < /tmp/changed.txt)
          if [ "$COUNT" -ne 1 ]; then
            echo "❌ Exactly one contributors file must be changed. Found: $COUNT"; exit 1
          fi

          FILE=$(cat /tmp/changed.txt)
          echo "file=$FILE" >> "$GITHUB_OUTPUT"

      - name: Verify PR author added their handle
        run: |
          FILE="${{ steps.onefile.outputs.file }}"
          echo "Checking file: $FILE"
          # Must contain a bullet line starting with the PR author's handle
          if ! grep -Eq "^- *@${{ github.actor }}\b" "$FILE"; then
            echo "❌ Your GitHub handle @${{ github.actor }} was not found as a bullet line in $FILE"
            echo "Add a line like: - @${{ github.actor }} — Your Name (Section: IT342-G0x)"
            exit 1
          fi
          echo "✅ Found @${{ github.actor }} in $FILE"

      # (Optional) Enforce only one added line in that file
      - name: Ensure only one new roster line was added (optional)
        run: |
          BASE="${{ steps.base.outputs.base_ref }}"
          FILE="${{ steps.onefile.outputs.file }}"
          ADDED=$(git diff --unified=0 "$BASE"...HEAD -- "$FILE" | grep -E '^\+' | grep -vE '^\+\+\+ ' | wc -l || true)
          if [ "$ADDED" -gt 3 ]; then
            echo "❌ Too many additions in $FILE. Add only your single roster line."
            exit 1
          fi
          echo "ℹ️ Added lines in $FILE: $ADDED"
